-- MySQL Script generated by MySQL Workbench
-- seg 03 mar 2025 20:01:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Desabilitar checagem de chaves únicas e chaves estrangeiras temporariamente para evitar erros durante a criação de tabelas.
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Criar o banco de dados `shopee` se não existir
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopee` DEFAULT CHARACTER SET utf8mb4;
USE `shopee`;



-- -----------------------------------------------------
-- Criar a tabela `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,  -- Coluna de ID autoincrementável
  `nome` VARCHAR(255) NULL DEFAULT NULL,                    -- Nome do usuário
  `email` VARCHAR(255) NULL DEFAULT NULL,                   -- Email do usuário
  `senha` VARCHAR(255) NULL DEFAULT NULL,                   -- Senha do usuário
  PRIMARY KEY (`idusuario`)                                -- Definindo a chave primária
) ENGINE = InnoDB                                           -- Usando o mecanismo de armazenamento InnoDB
DEFAULT CHARACTER SET = utf8mb4;                            -- Definindo o conjunto de caracteres como utf8mb4

-- Restaurando as configurações de verificação de chaves únicas e estrangeiras.
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Inserir dados na tabela `produtos`
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Criar a tabela `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,  -- Coluna de ID autoincrementável
  `nome` VARCHAR(255) NOT NULL,             -- Nome do produto (agora NOT NULL)
  `descricao` TEXT NULL DEFAULT NULL,       -- Descrição do produto (TEXT para mais espaço)
  `preco` DECIMAL(10,2) NOT NULL,           -- Preço do produto (agora NOT NULL)
  `imagem` VARCHAR(255) NULL DEFAULT NULL,  -- Caminho da imagem do produto
  `link` VARCHAR(255) NULL DEFAULT NULL,    -- Link de afiliado da Shopee
  `categoria` VARCHAR(100) NOT NULL,        -- Nova coluna de categoria
  PRIMARY KEY (`idproduto`)                 -- Definindo a chave primária
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- Inserindo alguns produtos de exemplo
INSERT INTO `produtos` (`nome`, `descricao`, `preco`, `imagem`, `link`, `categoria`) VALUES
('Smartphone Alpha', 'Smartphone com câmera de alta resolução e 128GB de armazenamento.', 1999.99, 'imagens/smartphone_alpha.jpg', 'https://shopee.com.br/smartphone-alpha', 'Eletrônicos'),
('Notebook Pro X', 'Notebook com processador i7, 16GB RAM e SSD de 512GB.', 4999.99, 'imagens/notebook_prox.jpg', 'https://shopee.com.br/notebook-prox', 'Informática'),
('Fone de Ouvido Bluetooth', 'Fone sem fio com cancelamento de ruído ativo.', 299.90, 'imagens/fone_bluetooth.jpg', 'https://shopee.com.br/fone-bluetooth', 'Áudio'),
('Cadeira Gamer Xtreme', 'Cadeira ergonômica com ajustes e almofadas para conforto.', 899.99, 'imagens/cadeira_gamer.jpg', 'https://shopee.com.br/cadeira-gamer', 'Móveis'),
('Relógio SmartFit', 'Relógio inteligente com monitoramento de batimentos cardíacos.', 359.90, 'imagens/smartfit.jpg', 'https://shopee.com.br/smartfit', 'Acessórios'),
('Teclado Mecânico RGB', 'Teclado gamer mecânico com iluminação RGB personalizável.', 450.00, 'imagens/teclado_rgb.jpg', 'https://shopee.com.br/teclado-rgb', 'Periféricos');

-- -----------------------------------------------------
-- Caso queira apagar o banco de dados, descomente a linha abaixo
-- DROP DATABASE shopee;
